debugging prerelease gate action

diff --git a/.github/workflows/pull_from_pre_release.yml b/.github/workflows/pull_from_pre_release.yml
--- a/.github/workflows/pull_from_pre_release.yml
+++ b/.github/workflows/pull_from_pre_release.yml
@@ -14,5 +14,8 @@ jobs:
       # if: ${{ !contains(github.event.pull_request.labels.*.name, 'actiongate-pre') }}
         if: ${{ !contains(github.event.pull_request.labels.name, 'actiongate-pre') }}
         run: |
-          echo "::error ::This PR must have the 'pre_release' label before it can be merged."
-          exit 1
+            echo "v 0.1"
+            echo "${{ github.event.pull_request.labels.name }}"
+            echo "${{ !contains(github.event.pull_request.labels.name, 'actiongate-pre') }}"
+            echo "::error ::This PR must have the 'pre_release' label before it can be merged."
+            exit 1
